version: "3.8"
services:
  uv-iga-iot-db:
    container_name: uv-iga-iot-db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: ${TZ}
    volumes:
      - ../../db-files:/var/lib/postgresql/data
    ports:
      - 9020:5432
    networks:
      - uv-iga

networks:
  uv-iga:
    name: uv-iga
